local colors = require("oradark.palette")

return {
    Oilfile = { fg = colors.light },
    OilfileHidden = { fg = colors.light },
    OilDir = { fg = colors.grey },
    OilDirHidden = { fg = colors.grey },
    OilDirIcon = { fg = colors.grey },
    OilSocket = { fg = colors.light },
    OilSocketHidden = { fg = colors.light },
    OilLink = { fg = colors.yellow },
    OilLinkHidden = { fg = colors.yellow },
    OilOrphanLink = { fg = colors.yellow },
    OilOrphanLinkHidden = { fg = colors.yellow },
    OilLinkTarget = { fg = colors.yellow },
    OilLinkTargetHidden = { fg = colors.yellow },
    OilOrphanLinkTarget = { fg = colors.yellow },
    OilOrphanLinkTargetHidden = { fg = colors.yellow },
    OilCreate = { fg = colors.orange },
    OilChange = { fg = colors.yellow },
    OilCopy = { fg = colors.orange },
    OilMove = { fg = colors.yellow },
    OilRestore = { fg = colors.green },
    OilDelete = { fg = colors.red },
    OilPurge = { fg = colors.red },
    OilTrash = { fg = colors.red },
    OilTrashSourcePath = { fg = colors.red },
}
